name: home
description: A home package.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: '>=3.0.0'

dependencies:
  authentication: ^0.0.1
  core: ^0.0.1
  dependencies: ^0.0.1
  flutter:
    sdk: flutter
  user_credentials: ^0.0.1
  wallet: ^0.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
