name: did_app_poc
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dev_dependencies:
  flutter_lints: ^5.0.0

workspace:
  - app
  - common/dependencies
  - common/core
  - common/network
  - features/authentication
  - features/home
  - features/user_credentials
