name: Apple Release

on:
  push:
    branches:
      - apple-release
  workflow_dispatch:

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Set up git and fetch all history for all branches and tags
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Bundle install for iOS Gemfile
        timeout-minutes: 5
        run: cd ./ios && bundle install
      - name: Get Flutter version from FVM
        id: fvm-version
        working-directory: .
        run: |
          FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
          echo "version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-version.outputs.version }}
          channel: "stable"
          architecture: x64
          cache: true
      - name: Set up melos
        run: flutter pub global activate melos
      - name: Melos Bootstrap
        run: melos bs
      - name: Build and Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_PAT_TOKEN }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
        run: |
          cd ./ios
          bundle exec fastlane release_beta
